---
title: "software_carpentry_10"
date: October 2, 2018
output: html_document
---

#Outline of a function:
```{r}
my_sum <- function(a, b) {
  the_sum <- a + b
  return(the_sum)
}
my_sum
```

#Fahrenheit to Kelvin function
```{r}
fahr_to_kelvin <- function(temp) {
  kelvin <- ((temp - 32) * (5 / 9)) + 273.15
  return(kelvin)
}

fahr_to_kelvin(32)
fahr_to_kelvin(212)
```


#Challenge 1
```{r}
kelvin_to_celcius <- function(temp) { 
  celcius <- temp - 273.15 
  return(celcius) 
}
```


#Challenge 2
```{r}
fahr_to_celsius <- function(temp) {
  temp_k <- fahr_to_kelvin(temp)
  result <- kelvin_to_celsius(temp_k)
  return(result)
}
```


#Checking functions with stopifnot()
```{r}
fahr_to_kelvin <- function(temp) {
  stopifnot(is.numeric(temp))
  kelvin <- ((temp - 32) * (5 / 9)) + 273.15
  return(kelvin)
}

fahr_to_kelvin(temp = as.factor(32))

```


#Challenge 3
```{r}
fahr_to_celsius <- function(temp) {
  stopifnot(is.numeric(temp))
  temp_k <- fahr_to_kelvin(temp)
  result <- kelvin_to_celsius(temp_k)
  return(result)
}

fahr_to_celsius(32)
```

#More on combining functions
```{r}
calcGDP <- function(dat) {
  gdp <- dat$pop * dat$gdpPercap
  return(gdp)
}

calcGDP(head(gapminder))

calcGDP <- function(dat, year=NULL, country=NULL) {
  if(!is.null(year)) {
    dat <- dat[dat$year %in% year, ]
  }
  if (!is.null(country)) {
    dat <- dat[dat$country %in% country,]
  }
  gdp <- dat$pop * dat$gdpPercap

  new <- cbind(dat, gdp=gdp)
  return(new)
}

head(calcGDP(gapminder, year = 2007))
calcGDP(gapminder, country = "Australia")
calcGDP(gapminder, country = "Australia", year = 2007)
```


#Challenge 4
```{r}

```












