---
title: "software_carpentry_11"
date: October 9, 2018
output: html_document
---

#Saving plots
```{r}
pdf("Life_Exp_vs_time.pdf", width=12, height=4)
ggplot(data=gapminder, aes(x=year, y=lifeExp, colour=country)) +
  geom_line() +
  theme(legend.position = "none")

# You then have to make sure to turn off the pdf device!

dev.off()
```

#Challenge 1
```{r}
pdf("Life_Exp_vs_time.pdf", width = 12, height = 4)
p <- ggplot(data = gapminder, aes(x = year, y = lifeExp, colour = country)) +
  geom_line() +
  theme(legend.position = "none")
p
p + facet_grid(. ~continent)
dev.off()
```


#Writing data (first need to write in gapminder data)
```{r}
gapminder = read.csv("data/gapminder-FiveYearData.csv")

aust_subset <- gapminder[gapminder$country == "Australia",]

write.table(aust_subset,
  file="data/gapminder-aus.csv",
  sep=","
)

write.table(
  gapminder[gapminder$country == "Australia",],
  file="data/gapminder-aus.csv",
  sep=",", quote=FALSE, row.names=FALSE
)
```


#Challenge 2
```{r}
write.table(
  gapminder[gapminder$year >= 1990,],
  file="cleaned-data/gapminder-1990",
  sep=",", quote=FALSE, row.names=FALSE
)
```






